name: Test

on:
    push:
        branches: [ "master", 'Dev*' ]
    pull_request:
        branches: [ "master" ]

jobs:
    checkstyle_and_test:
        name: checkstyle
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            pull-requests: write

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  java-version: '22'
                  distribution: 'temurin'
                  cache: maven

            - run: make lint
            - run: make test
